### DISCUSSION TITLE
Unknown manufacturer and product

### DISCUSSION THREAD

**Discussion by roblomq** [zwave-js/zwave-js-ui#2554] [Q&A]
In quite new on this so I got somehow can help me with this. I use OZW on Domoticz but have continues problems with it so I'm testing this zwavejs2MQTT. 
I've managed to install it in a Docker container on a Raspberry Pi. I can add nodes but all nodes I've tried (Fibaro FGMS001 and Aeotec recessed door sensor) but they came up with Unknown manufacturer and product and are missing settings and values.
I've tried excluding and including again, tried re-interviews but nothing helps. The interview state is completed. I found several bug reports that were about the same problem but they are marked as solved. Some say it should be solved with a re-interview but like I said, tried that but didn't since my problem.
How can I solve this?

**Comment by robertsLando** [comment]
How did you installed z2m? I feel like it's a problem with configuration database. Also please attach zwavejs driver logs

**Comment by roblomq** [comment]
I'm quite sure the problem is caused due to incorrect installation, I've searched quite extensive but there is not really a noob instruction from the start. So So I started with this instruction.
[https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker](https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker)
But that is assuming that docker is already installed. So getting docker up and running was a bit trial and error but I think it is working like it should.

"Installation" step 1 "Configure the path for your serial device" in the above instruction
It's not completely clear but with the help from another website I found out that this was the full name of the device in the "/dev/serial/by-id/" folder. In my case this was
`/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0`

Step 2 is setting the timezone.
It's not completely clear what the command should be. I think it should be "docker run -e TZ=Europe/Amsterdam" but then I get the error "docker run" requires at least 1 argument.". I assumed setting the timezone should also be possible later I moved on.

Step 3 
I want to use Domoticz so I'm not sure if I need the  Z-Wave JS web socket server? As the port 3000 is already in use by grafana I tried using 3001.

After that I got 3 options of installation but It's not clear what the advantages/disadvantages are or make a decision on what choice is best in my situation because there is no explanation whatsoever. 
The run as service is telling "To run ZWavejs2Mqtt as a service you can use the docker-compose.yml" but there is no instruction HOW to use it.
In the run in a local folder there is a "mkdir store" command but there is no instruction WHERE this folder should be created.
SO I picked the "Run using volumes" option. With the command below.

`docker run --rm -it -p 8091:8091 -p 3001:3000 --device=/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/zwave --mount source=zwavejs2mqtt,target=/usr/src/app/store zwavejs/zwavejs2mqtt:latest`

This gave 

> 2022-07-31 12:04:11.681 INFO APP: Version: 6.14.0
> 2022-07-31 12:04:11.714 INFO APP: Application path:/usr/src/app
> 
>  ______                       _     ___                  _   _
> |___  /                      (_)   |__ \                | | | |
>    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
>   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
>  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
> /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
>                             _/ |                      | |
>                            |__/                       |_|
> 
> 2022-07-31 12:04:11.827 WARN STORE: settings.json not found
> 2022-07-31 12:04:11.835 WARN STORE: scenes.json not found
> 2022-07-31 12:04:11.998 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
> 2022-07-31 12:04:12.255 WARN BACKUP: Store backup is disabled
> 2022-07-31 12:04:12.260 WARN BACKUP: Nvm backup is disabled
> 2022-07-31 12:04:12.270 WARN ZWAVE: Zwave driver not inited, no port configured
> 

And then nothing happens....

So I've googled further and then found another command and changed it to the settings I already found out so it became:
`docker run -d --name zwavejs2mqtt --restart unless-stopped -v /opt/zwavejs2mqtt/store:/usr/src/app/store -p 8091:8091 -p 3001:3000 --device=/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0  zwavejs/zwavejs2mqtt:latest`

And opening the url with port 8091 I got the ZWave2MQTT UI page. Everything seems to work but I don't get the manufacturer and device info and it seems not all configuration settings and values are there.

![2022-07-31_14h22_37](https://user-images.githubusercontent.com/59142034/182026316-88edca30-733b-47ae-b31d-9475021bb6b3.png)

**Comment by roblomq** [comment]
[zwavejs2mqtt_2022-07-31.log](https://github.com/zwave-js/zwavejs2mqtt/files/9228868/zwavejs2mqtt_2022-07-31.log)
I stopped the logging after the re-interview was on status completed for both test devices.

**Comment by roblomq** [comment]
Found another log file, not sure which one you need..
[zwavejs_2022-07-31.log](https://github.com/zwave-js/zwavejs2mqtt/files/9228887/zwavejs_2022-07-31.log)

**Comment by roblomq** [comment]
In the log it says

> 2022-07-31T18:05:58.820Z DRIVER   loading configuration...
> 2022-07-31T18:05:59.056Z CONFIG   Using external configuration dir /usr/src/app/store/.config-db
> 2022-07-31T18:05:59.058Z CONFIG   version 9.6.1
> 2022-07-31T18:05:59.452Z CONFIG   Could not load manufacturers config: The manufacturer config file does not exist! (ZW0340)
> 2022-07-31T18:06:01.671Z CONFIG   Could not load notifications config: The config file does not exist! (ZW0340)
> 2022-07-31T18:06:01.676Z CONFIG   Could not load scales config: The named scales config file does not exist! (ZW0340)
> 2022-07-31T18:06:01.681Z CONFIG   Could not load sensor types config: The sensor types config file does not exist! (ZW0340)
> 2022-07-31T18:06:01.689Z CONFIG   Could not meters config: The config file does not exist! (ZW0340)
> 2022-07-31T18:06:01.697Z CONFIG   Could not load indicators config: The config file does not exist! (ZW0340)

So i think that's the reason the right names and settings doesn't show up. The only question is why are these config files not loading?
I think it has to do with the docker mount settings, the folder  /usr/src/app/store/ is empty but I think the docker is running under /opt/zwavejs2mqtt/store somehow zwavejs2mqtt is not able to get the right config files but I don't know how to solve this. 
So I hope someone is able to help me?

**Comment by robertsLando** [comment]
Just copy the base docker-compose file into a folder, in this folder create also a `store` directory and map volume to this dir. Then run `docker-compose up -d` to start it.

```
mkdir zwavejs2mqtt
cd zwavejs2mqtt
// create docker-compose.yml file
mkdir store
```

Content of docker-compose.yml:

```yml
version: "3.7"
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want log times and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- TZ=America/New_York
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/insert_stick_reference_here:/dev/zwave'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```
