### DISCUSSION TITLE
Docker failing to start on LXC Proxmox - error creating device nodes

### DISCUSSION THREAD

**Discussion by devachnid** [zwave-js/zwave-js-ui#2708] [Q&A] [answered]
I'm using Debian 11 in an LXC on Proxmox 7.2
Docker v20.10.18, compose v 2.10.2

**docker-compose.yaml**
```
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=secret
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/London
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_1a1aae4d6794eb1181c632703d98b6d1-if00-port0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```
when I try and start the container I get the following error
```
root@zwave:~# docker compose up
[+] Running 1/1
 ⠿ Container zwave-js-ui  Recreated                                                                                                                                                                                                                    0.1s
Attaching to zwave-js-ui
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error creating device nodes: mount /dev/zwave:/var/lib/docker/overlay2/a195044c59330e1c0fdbf065475559621bb4bcc282724cd1b69f531c62b994e0/merged/dev/zwave (via /proc/self/fd/7), flags: 0x1000: no such file or directory: unknown
```

the device is correct:
```
root@zwave:~# ls -al /dev/serial/by-id
total 0
drwxr-xr-x 2 nobody nogroup 60 Oct  5 19:18 .
drwxr-xr-x 3 root   root    60 Oct  5 19:35 ..
lrwxrwxrwx 1 nobody nogroup 13 Oct  5 19:18 usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_1a1aae4d6794eb1181c632703d98b6d1-if00-port0 -> ../../ttyUSB0
```

This is my lxc.cong file:
```
arch: amd64
cores: 2
features: nesting=1
hostname: zwave
memory: 1024
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.1.1,hwaddr=8A:72:EF:02:BB:3E,ip=192.168.1.219/24,ip6=auto,type=veth
ostype: debian
rootfs: Data:vm-119-disk-0,size=4G
swap: 512
unprivileged: 1
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.mount.entry: /dev/serial/by-id               dev/serial/by-id         none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0                    dev/ttyUSB0             none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0                    dev/ttyACM0             none bind,optional,create=file
```

I've tried starting again, changing permissions etc - no luck

I notice that the /var/lib/docker/overlay2/.../merged directory does not exist - should it do before starting the container?

Thanks!
