### DISCUSSION TITLE
UI not loading on port 8091

### DISCUSSION THREAD

**Discussion by m-e-stew** [zwave-js/zwave-js-ui#2906] [Q&A] [answered]
Hi! I previously used zwavejs2mqtt, and was in the process of updating & moving over... and realized too late that my previous zwavejs2mqtt container was NOT successfully storing its configuration locally. So, starting from scratch, and I cannot reference back to my previous successful zwavejs2mqtt install. :(

I am hosting both my HA install and the zwavejsui install on Docker images using docker-compose on an Asustor NAS.

HA loads up and is accessible just fine from my NAS' address - http://192.168.10.9:8123 - but zwavejsui does not - http://192.168.10.9:8091 . I get a timeout error 

At the moment, I've got both in one docker-compose file. Obviously the two are different, but I can't figure out what's wrong with the way I'm setting up the 8091 port that it's not accessible in the same way HA's 8123 is... and how it used to be accessible in my zwavejs2mqtt install.

Looking at the container logs for ZWJSUI, there are no errors and it claims to be listening on 8091, but doesn't verify that it's using the NAS' IP address. Is there some kind of override to force it to use its host's IP address?

```
2023-01-23 03:46:10.704 INFO APP: Version: 8.7.0.3b57d81
2023-01-23 03:46:10.708 INFO APP: Application path:/usr/src/app
  ______  __          __                      _  _____     _    _ _____
 |___  /  \ \        / /                     | |/ ____|   | |  | |_   _|
    / /____\ \  /\  / /_ ___   _____         | | (___     | |  | | | |
   / /______\ \/  \/ / _' \ \ / / _ \    _   | |\___ \    | |  | | | |
  / /__      \  /\  / (_| |\ V /  __/   | |__| |____) |   | |__| |_| |_
 /_____|      \/  \/ \__,_| \_/ \___|    \____/|_____/     \____/|_____|

2023-01-23 03:46:10.725 WARN STORE: settings.json not found
2023-01-23 03:46:10.727 WARN STORE: scenes.json not found
2023-01-23 03:46:10.803 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
2023-01-23 03:46:10.846 WARN BACKUP: Store backup is disabled
2023-01-23 03:46:10.847 WARN BACKUP: Nvm backup is disabled
2023-01-23 03:46:10.849 WARN Z-WAVE: Z-Wave driver not inited, no port configured
```

This is the entire docker-compose file, including the HA bit.

```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /volume1/Docker/HomeAssistant/config:/config
    restart: always
    privileged: true
    network_mode: host
  zwavejsui:
    container_name: zwavejsui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=[]
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
    devices:
      - '/dev/ttyACM0:/dev/zwave'
    volumes:
      - /volume1/Docker/zwavejsui/store:/usr/src/app/store
    ports:
      - '3000:3000' # port for Z-Wave JS websocket server
      - '8091:8091' # port for Z-Wave JS ui
```

And this is the result of a docker inspect command on the container. I tried to cut out bits I thought were unrelated to networking, but I can post the full thing if it's helpful.

```
[
    {
        "Id": "600075cdd60078892fceb1121c15cc6b27ecf206e9214275a2e1d9da1c607631",
        "Created": "2023-01-23T03:45:47.21961866Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "node",
            "server/bin/www"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 25000,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-01-23T03:45:57.99308064Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
[...]
        "HostConfig": {
            "Binds": [
                "/volume1/Docker/zwavejsui/store:/usr/src/app/store:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "homeassistant_default",
            "PortBindings": {
                "3000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3000"
                    }
                ],
                "8091/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8091"
                    }
                ]
            },
[...]
        "Config": {
            "Hostname": "600075cdd600",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "3000/tcp": {},
                "8091/tcp": {}
            },
[...]
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e79a20692c7bf8ac8ef0e8a03f4915e9be3ef0fc95b3ca4c4b02563698419351",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3000"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "3000"
                    }
                ],
                "8091/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8091"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8091"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/e79a20692c7b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "homeassistant_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "zwavejsui",
                        "zwavejsui",
                        "600075cdd600"
                    ],
                    "NetworkID": "76e4373c62c4a7067021f7182e5d421ab7a2e98595c5e39e6b3dccf47a9f274e",
                    "EndpointID": "fb036126667d3c17a615a959de3acfa04520b2e0c8e1e9dd4030eefae005bf29",
                    "Gateway": "172.24.0.1",
                    "IPAddress": "172.24.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:18:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

Any help or thoughts would be really appreciated. I'm tearing my hair out, and super frustrated with myself for not noticing the previous local store was not actually up to date.
