### DISCUSSION TITLE
Update docker (as a service) zwave-js-ui

### DISCUSSION THREAD

**Discussion by dxfoxd** [zwave-js/zwave-js-ui#2990] [Q&A]
I'm using the docker container service for zwave-js-ui and recently the Home Assistant displayed a message that the "The version of Z-Wave JS Server you are currently running is too old for this version of Home Assistant. Please update the Z-Wave JS Server to the latest version to fix this issue.".  I'm using zwave-js-ui: 8.8.4.4f4cd65. 

My compose.yml had the following section for this container
```
 zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=[removed]
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=Europe/Amsterdam
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e63df2d83e94eb11adbf36703d98b6d1-if00-port0:/dev/zwave
    volumes:
      #- zwave-config:/usr/src/app/store
    # Or by using local folder
    - ./store:/config/zwave
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```

Tried to update using
```
sudo docker stop zwave-js-ui
sudo docker pull zwavejs/zwave-js-ui:latest
sudo docker start zwave-js-ui
```

The pull perfectly downloads and extracts the files, but after starting the container again I still notice the same (old) version number. I believe I'm missing something here, but hours of searching did not bring the solution. I saw an old post stating that I need to remove the old container, but doesn't this also remove all my device settings?

Peter
