### DISCUSSION TITLE
Home Assistant Zwave JS UI Proxy Plugin

### DISCUSSION THREAD

**Discussion by killtux** [zwave-js/zwave-js-ui#3024] [Q&A] [answered]
Would be cool if someone could make a proxy plugin like it's already existing for Zigbee2MQTT or Frigate if you run that service externally so you can have it in your Home Assistant Sidebar like its running directly in HA Supervisor:

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt-proxy
https://github.com/blakeblackshear/frigate-hass-addons/tree/main/frigate_proxy

**Comment by kpine** [comment, marked as answer]
I just use an iframe.

```yaml
panel_iframe:
  zwave:
    title: "Z-Wave"
    url: "https://hostname"
    icon: mdi:z-wave
```
