### DISCUSSION TITLE
Update Zwave-js-ui in docker and keep/save settings

### DISCUSSION THREAD

**Discussion by apella12** [zwave-js/zwave-js-ui#3269] [General]
Still a noob with docker and zwave-js-ui.  Using it with OpenHAB (rules and persistence). Found this suggestion 
`docker-compose pull && docker-compose up -d`
and it works, but the settings (like MQTT name, backup time, backup file, Zstick power settings) are lost. Using the example docker compose in the docs.  Docker seems to have a separate file structure and doesn't use the store in the yaml (AFAIK).
version: '3.7'
services:
```
    zwave-js-ui:
        container_name: zwave-js-ui
        image: zwavejs/zwave-js-ui:latest
        restart: always
        tty: true
        stop_signal: SIGINT
        environment:
            - SESSION_SECRET=mysupersecretkey
            - ZWAVEJS_EXTERNAL_CONFIG=/home/openhabian/zwave-js-ui/store/.config-db
            # Uncomment if you want log times and dates to match your timezone instead of UTC
            # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
            - TZ=America/New_York
        networks:
            - zwave
        devices:
            # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
            # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
            - '/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_88708347ca60ec11ac8a397625bfaa52-if00-port0:/dev/zwave'
        volumes:
        #    - zwave-config:/usr/src/app/store
        # Or by using local folder
            - ./store:/home/openhabian/zwave-ui-js/store
        ports:
            - '8091:8091' # port for web interface
networks:
    zwave:
volumes:
    zwave-config:
        name: zwave-config
```
