### DISCUSSION TITLE
How to read files from store inside docker volume

### DISCUSSION THREAD

**Discussion by DrSamjames** [zwave-js/zwave-js-ui#3482] [Q&A] [answered]
Hi

After a power cut my SD card that I was using to run ZWave JS on a Pi is no longer bootable. but I can still read the files off it. I've installed ZWave JS on a fresh card and my zwave controller still sees all my zwave devices but I've lost all the name and scene.

Is there a simple way to copy the store from my old SD card into my new installation? 

I’m using docker compose, this is my config at the moment which is basicly the same as the old one:

```
version: "3.7"
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      #- SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want log times and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/London
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/ttyAMA0:/dev/ttyAMA0'
    volumes:
      - zwave-config:/usr/src/app/store
   # Or by using local folder
   # - ./store:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config

```
