### DISCUSSION TITLE
TCP serial connection using rfc2217

### DISCUSSION THREAD

**Discussion by Oekel** [zwave-js/zwave-js-ui#3600] [Q&A] [answered]
Regarding **Docker** and having Devices on other machines its nice to support **ser2net** without using socat.
There is a working implementation in OpenHab I like to quote:
`rfc2217://<server>:<port>`
`rfc2217://extendzwavepi:3333`

Is it implemented allready? How to create correct formulated Issue for this?

Have a great day!

PS:
on server it looks like this:

> #add this to /etc/ser2net.yaml
connection: &Zwave
  accepter: telnet(rfc2217),tcp,3333
  connector: serialdev,
    /dev/zwavestick,
    115200n81 local

**Comment by robertsLando** [comment]
There are already many users using `ser2net` connections, just type (or paste) the address in the serial path in z-ui settings. That's a list but you can also provide a custom choice by typing it (it's a Combobox input)

**Reply by Oekel** [reply]
Found the doc on the old release:
[zwave-js](https://zwave-js.github.io/node-zwave-js/#/usage/tcp-connection)

Is it still same implementation?

Especially the mentioned point "raw, no timeout" I can not refind in given **ser2net.yaml** example.

**Reply by robertsLando** [reply]
> I can not refind in given ser2net.yaml example.

I never used it so I dunno, try and see

**Reply by Oekel** [reply, marked as answer]
Its working!

```
%YAML 1.1
---
# This is a ser2net configuration file, tailored to be rather
# simple.
#
# Find detailed documentation in ser2net.yaml(5)
# A fully featured configuration file is in
# /usr/share/doc/ser2net/examples/ser2net.yaml.gz
#
# If you find your configuration more useful than this very simple
# one, please submit it as a bugreport

define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &zwavestick
              accepter:tcp,4000
              enable: on
              options:
                kickolduser: true
              connector: serialdev,
                /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_5828e4a40755ed1186a193131d62bc44-if00-port0,
                115200n81,nobreak,local
```

Client (just):
`tcp://192.168.x.x:4000`

no luck with:
`rfc2217://<server>:<port>`
