### DISCUSSION TITLE
Driver stopped working on any upgrade post version 8.22.3

### DISCUSSION THREAD

**Discussion by r-zlo** [zwave-js/zwave-js-ui#3606] [General]
Hey folks, 

I'm a little stuck with the upgrade of my container zwave js ui container. 
In short I've got a VM which hosts my containers and seems that the zwave js container is no longer able to see the AOTEC gen5+ ZWave USB dongle after this version. 

Everything seems to work fine when I rollback to the previous version, so I don't suspect that there is any issue with the dongle, USB ports nor configuration, but happy get any suggestion. 

A friend of mine, who uses the same setup also hit the same issue when tryed to upgrade a few months back, which suggest that something has changed on the driver mapping since that version that breaks the USB pass throught once the container image is upgraded. 

Any help is much appreciated.
![image](https://github.com/zwave-js/zwave-js-ui/assets/89018409/ec6eceeb-f1ea-46dc-9c0e-37ce71d66760)

Error: 
```
Driver: Failed to open the serial port: Error: No such device or address, cannot open /.
Driver: Failed to open the serial port: Error: No such device or address, cannot open /dev/zwave (ZW0100)
Error: Driver: Failed to open the serial port: Error: No such device or address, cannot open /dev/zwave (ZW0100)


```

```
vm-iot2:~/docker/containers/zwave$ lsusb
Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd QEMU USB Tablet
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
vm-iot2:~/docker/containers/zwave$
```

here is a snipped of my docker-compose.yaml:
```

version: '3.5'
services:
  zwavejs2mqtt:
    container_name: zwave
    image: zwavejs/zwave-js-ui:9.2.3
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=XXXXXXXX
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db

    devices:
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave' 
    volumes:
      - zwave-config:/usr/src/app/store
     
volumes:
  zwave-config:
    name: zwave-config
```
