### DISCUSSION TITLE
Zwavejsui-ui container not started automatically (RPI)

### DISCUSSION THREAD

**Discussion by hvoorend** [zwave-js/zwave-js-ui#3653] [Q&A]
My MQTT-, zwavejsui-ui-, Domoticz-package runs perfectly fine and I’m happy with it. The only thing now is: my Mosquitto container is automatically started by docker-compose at RPI startup (after reboot or power on) but my zwavejs-ui container is not. I have to start it manually from /opt/zwavejs-ui/ with **docker-compose up -d** every time after power off/on or reboot. How can I make the zwavejsui-ui container auto start?
This is my docker-compose.yml:
`pi@raspberrypi:/opt/zwavejs-ui $ cat docker-compose.yml
version: "3.7"
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mySecretSession
      - TZ=Europe/Amsterdam
    devices:
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server `

This is my Mosquitto docker-compose.yaml
`pi@raspberrypi:/opt/mosquitto $ cat docker-compose.yaml
services:
  mosquitto:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
      - type: bind
        source: ./log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data" `

**Comment by hvoorend** [comment]
Apologies that I lost the formatting in the initial post. Here a retry:
My MQTT-, zwavejsui-ui-, Domoticz-package runs perfectly fine and I’m happy with it. The only thing now is: my Mosquitto container is automatically started by docker-compose at RPI startup (after reboot or power on) but my zwavejs-ui container is not. I have to start it manually from /opt/zwavejs-ui/ with **docker-compose up -d** every time after power off/on or reboot. How can I make the zwavejsui-ui container auto start?

This is my docker-compose.yml:

``` 
pi@raspberrypi:/opt/zwavejs-ui $ cat docker-compose.yml
version: "3.7"
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mySecretSession
      - TZ=Europe/Amsterdam
    devices:
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server 
```


This is my Mosquitto docker-compose.yaml:

```
pi@raspberrypi:/opt/mosquitto $ cat docker-compose.yaml
services:
  mosquitto:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
      - type: bind
        source: ./log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data" 
```
