### DISCUSSION TITLE
Docker w/ POE Controller Serial Timeout Fails to Restart

### DISCUSSION THREAD

**Discussion by efaden** [zwave-js/zwave-js-ui#4069] [Q&A]
I am running ZWave JS UI in a docker container within an Ubuntu VM on Proxmox.  The controller is a TubesZB ZWave controller with the Zooz module installed.  It seems to work fine for a time and then for some unknown reason ZWave JS UI exits with the error "Serial port errored: read ETIMEOUT".    This causes ZWave JS UI to crash.  So that's issue number one... I'm not sure why it gets a read timeout.  Issue number two is that when the docker goes to restart it gives 

```
08:33:46.184 DRIVER   Failed to initialize the driver: Error: Failed to lock DB file "/usr/src/app/s
                      tore/d699b88c.jsonl"!
                          at JsonlDB.open (/usr/src/app/node_modules/@alcalzone/jsonl-db/src/lib/db.
                      ts:407:10)
                          at Driver.initNetworkCache (/usr/src/app/node_modules/zwave-js/src/lib/dri
                      ver/Driver.ts:1559:3)
                          at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js
                      /src/lib/driver/Driver.ts:1709:4)
                          at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/drive
                      r/Driver.ts:1466:5)
```

So it seems that when the crash occurs due to the time out it isn't releasing the lock file.  Manually killing, removing, and restarting the docker seems to be required to get it to come back up.  

Any suggestions?

**Comment by robertsLando** [comment]
Could you share your docker-compose.yml file or the docker command you are using to start zui?

**Reply by efaden** [reply]
Sorry for the delay.  

```
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    env_file: .env
    environment:
      - SESSION_SECRET
      - TZ
    networks:
      - traefik_default
    volumes:
      - ./data:/usr/src/app/store
    # Or by using local folder
    # - ./store:/usr/src/app/store
    healthcheck:
      test: 'wget --no-verbose --spider --no-check-certificate --header "Accept:
        text/plain" http://localhost:8091/health || exit 1'
      interval: 1m
      timeout: 10s
      start_period: 30s
      retries: 3
      #ports: null
      # - 8091:8091 # port for web interface
      # - 3000:3000 # port for Z-Wave JS websocket server
    labels:
      - traefik.enable=true
      - traefik.http.routers.zwavejsui.entrypoints=https-internal
      - traefik.http.routers.zwavejsui.rule=Host(`zwavejsui.<DOMAIN>`)
      - traefik.http.routers.zwavejsui.middlewares=internal-chain@file
      - traefik.http.routers.zwavejsui.tls=true
      - traefik.http.routers.zwavejsui.service=zwavejsui
      - traefik.http.services.zwavejsui.loadbalancer.server.port=8091
      - traefik.http.routers.zwavejsui-ws.entrypoints=https-internal
      - traefik.http.routers.zwavejsui-ws.rule=Host(`zwavejsui-ws.<DOMAIN>`)
      - traefik.http.routers.zwavejsui-ws.middlewares=internal-chain@file
      - traefik.http.routers.zwavejsui-ws.service=zwavejsui-ws
      - traefik.http.services.zwavejsui-ws.loadbalancer.server.port=3000
networks:
  traefik_default:
    external: true
```
