### DISCUSSION TITLE
Migrating my zwave JS UI to new SD card

### DISCUSSION THREAD

**Discussion by Rouzax** [zwave-js/zwave-js-ui#4258] [Q&A]
I have an existing installation on a SD card for my RPi 4 with Zwave JS
```
zwave-js-ui: 10.5.1.b5cf23c
zwave-js: 15.4.2
home id: 3244133030
home hex: 0xc15d8aa6
```

docker-compose.yml
```yml
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=-------------------------
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Amsterdam
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
      # - '/dev/ttyACM0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```

I want to create a new SD card with the latest version of Rasbian OS and depoly a new docker of zwave JS UI and restore all my settings, nodes names, etc. Will keep using the same RPi and Zwave stick

How do I backup and restore everything?
I tried to export and import the settings.json and the nodes.json but that does not seem to work
