### DISCUSSION TITLE
_EVENTS and Home Assistant

### DISCUSSION THREAD

**Discussion by rikdc** [zwave-js/zwave-js-ui#574] [Q&A]
I have a Zen34 scene controller and trying to figure out how to integrate it with Home-Assistant with MQTT. I've seen some state updates, but also wondered if the _EVENTS topic will be more stable. I'm confused on how these are meant to be integrated. Is there any relevant documentation available?

Update:

I first created a sensor that listened to the MQTT event. Automations would trigger with template conditions:

```
   condition:
   - condition: template
     value_template: '{{ trigger.payload_json.data[0].id|int == 82 }}'
   action:
```

Although this worked, it was slow and doesn't scale. I've now created an automation that listens to the change, and triggers internal events.

```
- alias: ZWave Event Monitor
  description: ''
  trigger:
  - platform: mqtt
    topic: homeassistant/_EVENTS/ZWAVE_GATEWAY-homeassistant/node/node_value_updated
  action:
    - event: zwave.node_value_updated
      event_data:
        node_id: "{{ trigger.payload_json.data[0].id|int }}"
        scene: "{{ trigger.payload_json.data[1] }}"
```

And then subsequent automatons can be triggered by the event.
