### ISSUE TITLE
error "Error parsing config file lzw31-sn.json" in logs

### ISSUE THREAD

**Issue by josh-m-sharpe** [zwave-js/zwave-js-ui#2774]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.2.2

### ZwaveJS version

eh?

### Describe the bug

Noticed This error in my logs.  What are the implications of this and how do I resolve it?

```
zwavejs    | 12:48:07.166 CONFIG   Error parsing config file lzw31-sn.json: Could not parse config file /usr/src/
zwavejs    |                       app/store/config/templates/master_template.json: ENOENT: no such file or direc
zwavejs    |                       tory, open '/usr/src/app/store/config/templates/master_template.json'
zwavejs    |                       Import stack:
zwavejs    |                         in #base_enable_disable
zwavejs    |                         in /usr/src/app/store/config/lzw31-sn.json (ZW0340)
```

### To Reproduce

(re)start docker container

### Expected behavior

no errors on startup

**Comment by josh-m-sharpe** [comment]
Seems like these inovelli json files are referencing some file at `~/templates/master_template.json` -- which isn't there.

```
$ docker-compose exec zwavejs2mqtt /bin/sh
/usr/src/app # ls /usr/src/app/store/config/
lzw30-sn.json  lzw31-sn.json

/usr/src/app # ls /usr/src/app/store/config/template
ls: /usr/src/app/store/config/template: No such file or directory


/usr/src/app # grep master /usr/src/app/store/config/lzw31-sn.json
			"$import": "~/templates/master_template.json#base_enable_disable",
			"$import": "~/templates/master_template.json#base_0-99_nounit",
			"$import": "~/templates/master_template.json#base_0-99_nounit",
			"$import": "~/templates/master_template.json#base_0-99_nounit",
			"$import": "~/templates/master_template.json#base_0-100_nounit",
			"$import": "~/templates/master_template.json#base_0-100_nounit",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"$import": "~/templates/master_template.json#base_enable_disable",
```

**Comment by josh-m-sharpe** [comment]
Seems like these files aren't there on the image -- so how do they get there?

``` 
docker run -it --rm zwavejs/zwave-js-ui:8.2.2 /bin/sh
/usr/src/app # ls /usr/src/app/store/
/usr/src/app #
```

**Comment by robertsLando** [comment]
Could you show me your docker-compose file? Are you using a custom `STORE_DIR` end var? Did you changed the `ZWAVEJS_EXTERNAL_CONFIG` env var?

**Comment by josh-m-sharpe** [comment]
Thanks for looking!

```
version: '3.3'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwave-js-ui:8.2.2
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - ZWAVEJS_DISABLE_SOFT_RESET=false
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- TZ=America/New_York
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      # - '/dev/serial/by-id/insert_stick_reference_here:/dev/zwave'
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server

networks:
  zwave:
volumes:
  zwave-config:
```
