### ISSUE TITLE
Using Homeassistant to change the state of a z-wave wall Plug causes crash in zwavejsui

### ISSUE THREAD

**Issue by merlink01** [zwave-js/zwave-js-ui#2876]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Z-Wave JS UI version

8.6.2

### ZwaveJS version

10.3.1

### Describe the bug

Using Homeassistant to change the state of a z-wave wall Plug causes crash in zwavejsui.

ERROR Z-WAVE-SERVER: Unexpected error label.toString(...).toLowerCase(...).replaceAll is not a function
TypeError: label.toString(...).toLowerCase(...).replaceAll is not a function
at zwaveLabel (/snapshot/zwave-js-ui/node_modules/@kvaster/zwavejs-prom/index.js:50:10)
at ZwavejsProm.onValueChanged (/snapshot/zwave-js-ui/node_modules/@kvaster/zwavejs-prom/index.js:161:34)
at ZwaveClient.emit (events.js:400:28)
at ZwaveClient.emit (domain.js:475:12)
at ZwaveClient.emitValueChanged (/snapshot/zwave-js-ui/server/lib/ZwaveClient.js:908:14)
at ZwaveClient._updateValue (/snapshot/zwave-js-ui/server/lib/ZwaveClient.js:3017:26)
at ZwaveClient._onNodeValueUpdated (/snapshot/zwave-js-ui/server/lib/ZwaveClient.js:2504:14)
at ZWaveNode.emit (events.js:412:35)
at ZWaveNode.emit (domain.js:475:12)
at ZWaveNode.translateValueEvent (/snapshot/zwave-js-ui/node_modules/zwave-js/src/lib/node/Node.ts:466:8)

### To Reproduce

Setup as lxc container on a Proxmox host:
https://tteck.github.io/Proxmox/
https://github.com/tteck/Proxmox/raw/main/ct/zwave-js-ui-v5.sh

Using Homeassistant to change the state of a z-wave wall Plug.

### Expected behavior

It shouldn't crash.

**Comment by merlink01** [comment]
Thank you but most of my devices are zwave, so ha is not really usable with the plugin deactivated ;-)
PS, i switched new from the old zwavejs to zwavejsui implementation.
Also values are not updating anymore in ha, so automations don't work.
I hope that's all the same error.

**Comment by merlink01** [comment]
No, i don't use Prometheus. only zwavejsui + homeassistant.
an example is a heater build from a switch and a multisensor:

```
climate:
  - platform: generic_thermostat
    name: Heizung Schlafzimmer
    unique_id: thermo.schlafzimmer
    heater: switch.switch_schlafzimmer
    target_sensor: sensor.sensor_schlafzimmer_air_temperature
    min_temp: 0
    max_temp: 30
    target_temp: 18
    hot_tolerance: 1
    cold_tolerance: 0.3
    initial_hvac_mode: "heat"
    precision: 0.1
    cold_tolerance: 1
```
