### ISSUE TITLE
Unable to update container to :latest via watchtower

### ISSUE THREAD

**Issue by nitobuendia** [zwave-js/zwave-js-ui#2920]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.8.1.86d7bf4

### ZwaveJS version

10.5.0

### Describe the bug

When running watchtower to update cointainers, I get the following error:

```
Could not do a head request for "zwavejs/zwavejs2mqtt:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```

This did not happen before. The first occurence started on Jan 28th. It seems related to [these changes](https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053). For example, pihole had the same error but they fixed it. The issue also contains links to instructions on how to solve it.

### To Reproduce

Set up a container with `:latest` via docker-compose.yaml

```yaml
version: "3.7"

services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=Asia/Singapore
    env_file:
      - ./secrets.env
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Z-Wave
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - "8091:8091" # Web interface.
      - "3000:3000" # zwave-js websocket server.
```

Set up watchtower to auto-update via docker-compose:

```yaml
version: "3"

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    env_file:
      - ./common.env
    environment:
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./run:/run
```

### Expected behavior

Container should auto-update.
