### ISSUE TITLE
Following the official docker compose - storage not persistant

### ISSUE THREAD

**Issue by moskovskiy82** [zwave-js/zwave-js-ui#3136]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

Latest

### ZwaveJS version

Latest

### Describe the bug

Following the official docker compose yaml

```
#https://zwave-js.github.io/zwave-js-ui//#/getting-started/quick-start
version: '3.7'
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=xxx
      - ZWAVEJS_EXTERNAL_CONFIG=/istorage/storage/Docker/Hass/zwave/.config-db
      - TZ=Europe/Moscow
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - zwave-config:/istorage/storage/Docker/Hass/zwave/
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```
Upon every upgrade get a vanilla fresh installstion

### To Reproduce

Follow the official docker compose

### Expected behavior

Settings stay upon upgrades
