### ISSUE TITLE
High CPU on my Docker Daemon from  ZvaveJS even without any data

### ISSUE THREAD

**Issue by 03397** [zwave-js/zwave-js-ui#3323]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.0.3.c37f5a4

### ZwaveJS version

12.0.2

### Describe the bug

I am running a docker instance on my QNAP NAS.
I have several containers utilizing almost 0% CPU utilization.
When I start the zwavejs container I have continuous spikes to my CPU from 10-60%  which can be seen on my dockerd process.
The actual container  is 0%.
The dockerd starts like this
container-station/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --bridge=lxcbr0 --tlsverify --tlscacert=/etc/docker/tls/ca.pem --tlscert=/etc/docker/tls/server.pem --tlskey=/etc/docker/tls/server-key.pem --storage-driver=overlay2 --dns 10.0.3.1 --data-root=/var/lib/docker --exec-root=/var/run/docker --pidfile=/var/run/docker.pid -D --userland-proxy=false --config-file /share/CACHEDEV2_DATA/.qpkg/container-station/etc/docker.json

and the zvavejs docker-compose.yaml file is the following

```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- TZ=America/New_York
      - TZ=Asia/Nicosia
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/ttyACM0:/dev/zwave'
    volumes:
      - /share/Container/container-station-data/lib/docker/volumes/zwavejs2mqtt/_data:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```

Also 

```json
{
	"mqtt": {
		"name": "Zwavejs2Mqtt",
		"host": "localhost",
		"port": 1883,
		"qos": 1,
		"prefix": "zwave",
		"reconnectPeriod": 3000,
		"retain": true,
		"clean": true,
		"auth": false,
		"_ca": "",
		"ca": "",
		"_cert": "",
		"cert": "",
		"_key": "",
		"key": "",
		"disabled": true
	},
	"gateway": {
		"type": 0,
		"plugins": [],
		"authEnabled": false,
		"payloadType": 0,
		"nodeNames": true,
		"hassDiscovery": true,
		"discoveryPrefix": "homeassistant",
		"logEnabled": true,
		"logLevel": "info",
		"logToFile": true,
		"values": [
			{
				"device": "134-129-2",
				"value": {
					"id": "128-0-level",
					"commandClass": 128,
					"commandClassName": "Battery",
					"endpoint": 0,
					"property": "level",
					"propertyName": "level",
					"type": "number",
					"readable": true,
					"writeable": false,
					"label": "Battery level",
					"stateless": false,
					"commandClassVersion": 1,
					"min": 0,
					"max": 100,
					"unit": "%",
					"list": false,
					"value": 100,
					"lastUpdate": 1651141622750
				},
				"enablePoll": true,
				"pollInterval": 3600
			},
			{
				"device": "134-130-2",
				"value": {
					"id": "128-0-level",
					"commandClass": 128,
					"commandClassName": "Battery",
					"endpoint": 0,
					"property": "level",
					"propertyName": "level",
					"type": "number",
					"readable": true,
					"writeable": false,
					"label": "Battery level",
					"stateless": false,
					"commandClassVersion": 1,
					"min": 0,
					"max": 100,
					"unit": "%",
					"list": false,
					"value": 47,
					"lastUpdate": 1651141622845
				},
				"enablePoll": true,
				"pollInterval": 3600
			}
		],
		"jobs": [],
		"https": false
	},
	"zwave": {
		"port": "/dev/zwave",
		"allowBootloaderOnly": false,
		"commandsTimeout": 30,
		"logLevel": "info",
		"rf": {
			"txPower": {
				"powerlevel": 0,
				"measured0dBm": 0
			},
			"region": 0
		},
		"logEnabled": true,
		"securityKeys": {
			"S2_Unauthenticated": "x",
			"S2_AccessControl": "x",
			"S2_Authenticated": "x",
			"S0_Legacy": "x"
		},
		"deviceConfigPriorityDir": "/usr/src/app/store/config",
		"logToFile": true,
		"maxFiles": 7,
		"serverEnabled": true,
		"serverServiceDiscoveryDisabled": false,
		"enableSoftReset": true,
		"enableStatistics": true,
		"serverPort": 3000,
		"maxNodeEventsQueueSize": 100,
		"higherReportsTimeout": false,
		"disclaimerVersion": 1
	},
	"backup": {
		"storeBackup": false,
		"storeCron": "0 0 * * *",
		"storeKeep": 7,
		"nvmBackup": false,
		"nvmBackupOnEvent": false,
		"nvmCron": "0 0 * * *",
		"nvmKeep": 7
	}
}
```

This think is driving me nuts.
Your help will be  appreciated.

### To Reproduce

Start zwavejs container

### Expected behavior

Low CPU
