### ISSUE TITLE
Trouble finding comliant devices

### ISSUE THREAD

**Issue by FritsdeGroot** [zwave-js/zwave-js-ui#3386]
Hi,

For a while am I trying to upgrade my Zwave system from OpenZwave to Zwave-JS-UI, as advised by Domoticz. Thanks to the eloborate documentation I found my way through but I am stuck on the last hurdle (I hope ;-))

The network recognizes only the controller but not the single device in the network I have configured. This device works properly in my current Open Zwave configuration.

This is what I get on my network with Zwave-JS-UI
![afbeelding](https://github.com/zwave-js/zwave-js-ui/assets/47210344/8498821c-7897-467e-88a7-05a61cf38954)

Device number 08 is a ZW100 Multisensor from Aeotec https://devices.zwave-js.io/?jumpTo=0x0086:0x0002:0x0064:0.0

But if I tried to find it in the Zwave-JS config library I get:
![afbeelding](https://github.com/zwave-js/zwave-js-ui/assets/47210344/8bf44e63-7e1b-45da-a469-8aeb56c16cf7)

I am running Zwave-JS-UI on a rapberry Pi with Docker Compose installed

```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```
`Docker Compose version v2.21.0
`

With the following docker-compose.yml config

```
version: '3.7'
services:
    zwave-js-ui:
        container_name: zwave-js-ui
        image: zwavejs/zwave-js-ui:latest
        restart: always
        tty: true
        stop_signal: SIGINT
        environment:
            - SESSION_SECRET=0203090109060708090A0B0C0D0E0F10
            - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
            # Uncomment if you want log times and dates to match your timezone instead of UTC
            # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
            - TZ=Europe/Amsterdam
        networks:
            - zwave
        devices:
           # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
           # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
            - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
        volumes:
            - zwave-config:/usr/src/app/store
        # Or by using local folder
        # - ./store:/usr/src/app/store
        ports:
            - '8091:8091' # port for web interface
            - '3000:3000' # port for Z-Wave JS websocket server

#    zigbee2mqtt:
#        container_name: zigbee2mqtt
#        image: koenkk/zigbee2mqtt
#        restart: unless-stopped
#        volumes:
#            - ./data:/app/data
#            - /run/udev:/run/udev:ro
#        ports:
#            # Frontend port
#            - '8090:8090'
#        environment:
#            - TZ=Europe/Amsterdam
#        devices:
#            # Make sure this matched your adapter location
#            - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCC56B4-if00:/dev/ttyACM0
networks:
    zwave:
volumes:
    zwave-config:
        name: zwave-config
```

I have added the log files and the nodes.json to the question. If you are able to provide me some pointers it would be much appreciated.

Kind regards
Frits de Groot

[nodes_dump.json](https://github.com/zwave-js/zwave-js-ui/files/13198881/nodes_dump.json)
[zwave-js-ui-store.zip](https://github.com/zwave-js/zwave-js-ui/files/13198882/zwave-js-ui-store.zip)
