### ISSUE TITLE
After Update QNAP Container Armv7 Not working

### ISSUE THREAD

**Issue by mupsje** [zwave-js/zwave-js-ui#3449]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

zwavejs/zwave-js-ui:latest

### ZwaveJS version

zwavejs/zwave-js-ui:latest

### Describe the bug

After update not working 

### To Reproduce

installed zwavejs/zwave-js-ui:sha-2cde5d2

the it worked again.

### Expected behavior

need to change armv7 Qnap

below code always worded till today after update

### Additional context

```
version: "3"
services:
 zwavejs2mqtt:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave2mqtt
    restart: always
    tty: true
    stop_signal: SIGINT
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
      - '/dev/ttyACM0:/dev/zwave'
    volumes:
     - /share/docker/zwave/store:/usr/src/app/store/
     - /share/docker/zwave:/data
    networks:
      vlan86:
      
    mac_address: blalalalalalalalala
    ports:
      - '8091:8091'
      - '3000:3000'
    environment:
      - PUID=502
      - PGID=100
      - SESSION_SECRET=blablalblalblalblalbla
      - TZ=Europe/Amsterdam

networks:
  vlan86:
    name: qnet-static-vlan86
    external: true
```
