### ISSUE TITLE
Z-Wave not working anymore

### ISSUE THREAD

**Issue by jcouzy** [zwave-js/zwave-js-ui#3586]
I receive these messages:

2024-02-08 08:48:53.522 INFO APP: Version: 9.8.3.3e632db
2024-02-08 08:48:53.525 INFO APP: Application path:/usr/src/app
  ______  __          __                      _  _____     _    _ _____ 
 |___  /  \ \        / /                     | |/ ____|   | |  | |_   _|
    / /____\ \  /\  / /_ ___   _____         | | (___     | |  | | | |  
   / /______\ \/  \/ / _' \ \ / / _ \    _   | |\___ \    | |  | | | |  
  / /__      \  /\  / (_| |\ V /  __/   | |__| |____) |   | |__| |_| |_ 
 /_____|      \/  \/ \__,_| \_/ \___|    \____/|_____/     \____/|_____|
2024-02-08 08:48:53.536 WARN STORE: settings.json not found
2024-02-08 08:48:53.542 WARN STORE: scenes.json not found
2024-02-08 08:48:53.552 INFO APP: Listening on port 8091 protocol HTTP
2024-02-08 08:48:53.572 WARN BACKUP: Store backup is disabled
2024-02-08 08:48:53.573 WARN BACKUP: Nvm backup is disabled
2024-02-08 08:48:53.574 WARN Z-WAVE: Z-Wave driver not inited, no port configured

Here's my device:
jcouzy@odroid:~$ ls -l /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_0cc409490755ed1184a19c131d62bc44-if00-port0
lrwxrwxrwx 1 root root 13 Feb  8 08:44 /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_0cc409490755ed1184a19c131d62bc44-if00-port0 -> ../../ttyUSB0

[ 3023.836247] usb 1-2: cp210x converter now attached to ttyUSB0
[ 3579.389013] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[ 3724.888859] usb 1-3: cp210x converter now attached to ttyUSB0

So hardware is found, but driver not inited, both while listed in the docker compose as /dev/ttyUSB0 and /dev/serial/by-id

What could possibly be wrong? All worked before flawless.

**Comment by robertsLando** [comment]
@jcouzy You should open the ui on port 8091 and add the settings, there are no settings saved

**Comment by yqiang** [comment]
I'm running into the same issue when trying to set up zwavejs on a new computer via docker (and docker-compose.yml).

**Comment by robertsLando** [comment]
I need to see your docker-compose file guys because there must be an issue there otherwise ALL users would be affected by this

**Comment by Oekel** [comment]
Also for me having problems to setup this docker stuff (regarding /dev/tty or /dev/customvirtualname)
so Would be nice to see some docker-compose as examples where we could continue discussion. (Would not like to post mine because I am just starting to experiment)

Would like to see some configs that worked in the past. Thanks a lot!

**Comment by robertsLando** [comment]
This is the base one: https://github.com/zwave-js/zwave-js-ui/blob/master/docker/docker-compose.yml

You should just change the tty mapping by looking for your local `/dev/serial/by-id/` devices, see https://github.com/zwave-js/zwave-js-ui/discussions/2483 to find out how

**Comment by yqiang** [comment]
Here's my `docker-compose.yml` file. I think it's more or less the same as the example one, minus the /dev entry.

```
version: '3.7'
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- TZ=America/New_York
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      #      - '/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0001-if00-port0:/dev/zwave'
      - '/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0001-if00-port0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```
