### ISSUE TITLE
Zwavejs not starting after docker upgrade and reboot.

### ISSUE THREAD

**Issue by jaimevisser** [zwave-js/zwave-js-ui#3860]
Did an apt-get upgrade to update my ubuntu machine running HA + zwave-js-ui and finished with a reboot to boot into the new kernel.
![image](https://github.com/user-attachments/assets/6a7efac4-0794-4c25-868e-7a7a55d52c02)

There's nothing in both the docker logs and zwavejs logs after the reboot. I tried shutting down the container and moving the content of the store mount to a different location (in effect a first boot) and the error persists. Updating to zwavejs 9.17.0 also does not fix the problem.

Docker: Docker version 27.1.2, build d01f264
Ubuntu: Ubuntu 22.04.4 LTS

Relevant compose section (hostname redacted):
```
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwave-js-ui:9.12.0
    restart: unless-stopped
    tty: true
    privileged: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=QE4P2LOKxGrytZTRCXo8
    volumes:
      - ./zwavejs2mqtt:/usr/src/app/store
      - /dev:/dev
    ports:
      - '3000:3000' # port for zwave-js websocket server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zwave.entrypoints=websecure"
      - "traefik.http.routers.zwave.rule=Host(`zwave.***.**`)"
      - "traefik.http.routers.zwave.middlewares=auth@file"
      - "traefik.http.services.zwave.loadbalancer.server.port=8091"
```
