### ISSUE TITLE
invoke API Multi Channel Encapsulation Command Home assistant

### ISSUE THREAD

**Issue by mattia93cz** [zwave-js/zwave-js-ui#4199]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

10.1.5.c36c719

### ZwaveJS version

15.0.5

### Describe the bug

Hi guys.
I would like to send the multichannel encapsulation command with a binary switch to turn off multiple lights (endpoints) at the same time.
I have tried several times changing the syntax but I always get an error: 

zwave_js.invoke_cc_api Endpoint(node_id=3, index=0) - FailedCommand: unknown_error: TypeError: this.encapsulated.serialize is not a function at MultiChannelCCCommandEncapsulation2.serialize (/usr/src/app/node_modules/@zwave-js/cc/src/cc/MultiChannelCC.ts:1460:28) at SendDataBridgeRequest2.serializeCC (/usr/src/app/node_modules/@zwave-js/serial/src/serialapi/transport/SendDataBridgeMessages.ts:178:43) at Driver.exceedsMaxPayloadLength (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:7852:34) at simpleMessageGenerator (/usr/src/app/node_modules/zwave-js/src/lib/driver/MessageGenerators.ts:140:39) at AsyncGenerator.next (<anonymous>) at maybeTransportServiceGenerator (/usr/src/app/node_modules/zwave-js/src/lib/driver/MessageGenerators.ts:244:17) at AsyncGenerator.next (<anonymous>) at gen (/usr/src/app/node_modules/zwave-js/src/lib/driver/MessageGenerators.ts:981:41) at gen.next (<anonymous>) at Transaction.generateNextMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Transaction.ts:149:49).

what am I doing wrong?
thanks in advance

### To Reproduce

```
action:` zwave_js.invoke_cc_api
data:
  device_id:
    - 1b91e4e4bbe15a3788a8a2535e997f5d
  command_class: "96"
  method_name: sendEncapsulated
  parameters:
    - encapsulated:
        command_class: "37"
        method_name: set
        device_id: 1b91e4e4bbe15a3788a8a2535e997f5d
        value: false
      destination: "123456"
```

### Expected behavior

Multi Channel Encapsulation Command’ with a ‘Switch Binary’ to shut down 6 endpoints with a single zwave message.

**Comment by mattia93cz** [comment]
Hi @kpine! sorry you're right.  
here is the modified code:

```
action: zwave_js.invoke_cc_api
data:
  device_id:
    - 1b91e4e4bbe15a3788a8a2535e997f5d
  command_class: "96"
  method_name: sendEncapsulated
  parameters:
    - encapsulated:
        command_class: "37"
        method_name: set
        device_id: 1b91e4e4bbe15a3788a8a2535e997f5d
        value: false
      destination: "123456"
```

I have already opened a discussion on home assistant but I have not received support.
