### ISSUE TITLE
Docker image upgrade results in unresolved ProtocolInfo under Interview

### ISSUE THREAD

**Issue by polskikrol** [zwave-js/zwave-js-ui#4209]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

zwave-js-ui: 10.3.1.d1f0205

### ZwaveJS version

zwave-js: 15.1.0

### Describe the bug

A picture is worth a thousand words, so here it is..

<img width="339" alt="Image" src="https://github.com/user-attachments/assets/74768a82-db06-4637-bdb4-4552ab189789" />

Essentially, each time I perform a docker compose to update the image, I have to re-interview all nodes again. Otherwsise, while everything updates fine, I only see ProtocolInfo and it spins under Interview for all nodes. The issue is resolved after some time when I manually select and re-interview all nodes all over again.

### To Reproduce

Update docker container to new code upon release availability. Look at the Interview column.

### Expected behavior

One should have to re-interview all nodes. Something appears to be unset in the initialization of a new docker instance version of zwave-js-ui.

**Comment by polskikrol** [comment]
```
services:
  zwave-js-ui:
    image: 'zwavejs/zwave-js-ui:latest'
    container_name: 'zwave-js-ui'
    hostname: 'zwave-js-ui'
    networks:
      docker_bridge:
        ipv4_address: '172.16.0.1'
    tty: true
    stop_signal: 'SIGINT'
    environment:
      - SESSION_SECRET='REDACTED'
      - ZWAVEJS_EXTERNAL_CONFIG='/usr/src/app/store/.config-db'
      - TZ=US/Eastern
    volumes:
      - /docker/zwave-js-ui/files:/usr/src/app/store
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_d89512360a55ed11b62e91131d62bc44-if00-port0:/dev/zwave
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
    restart: 'unless-stopped'
networks:
  docker_bridge:
    external: true
````

**Comment by polskikrol** [comment]
[zwave-js-ui-store.zip](https://github.com/user-attachments/files/19896972/zwave-js-ui-store.zip)

Attached logs with debug on. Seeing this issue now.

**Comment by polskikrol** [comment]
I see the same issue when I just modify my docker yaml and rebuild the instance. Nothing indicative in logs.

I still had an old environmental variable:

 #      - ZWAVEJS_EXTERNAL_CONFIG='/usr/src/app/store/.config-db'

So. I commented it. Restarted the container and at least saw the files updating with new timestamps. However, same behaviour... every device shows up with ProtocolInfo and a spinning status bar. It is not until I highlight all device and re-interview them that this goes away.

A docker image rebuild or an upgrade should not require re-interviewing every device!

**Comment by robertsLando** [comment]
I think the problem was the ZWAVEJS_EXTERNAL_CONFIG env var, that is not needed

**Comment by polskikrol** [comment]
Even after removing it.. I see the same issue when I restart the container.
It simply wants to reinterview everything and Protocol spinning continues.

**Comment by robertsLando** [comment]
@polskikrol I checked your logs and yeah I noticed that them are tucked on that interview stage but I don't see any error apparently, need to ask @AlCalzone to give a look at them. Could you also try to upgrade to latest? I know many errors have been fixed in latest versions since first v15 release

**Comment by polskikrol** [comment]
Upgraded a few days ago, so here are the updated versions from the docker container:

```
zwave-js-ui: 10.5.1.b5cf23c
zwave-js: 15.4.2
```

The following is my docker file:

```
services:
  zwave-js-ui:
    image: 'zwavejs/zwave-js-ui:latest'
    container_name: 'zwave-js-ui'
    hostname: 'zwave-js-ui'
    networks:
      docker_bridge:
        ipv4_address: '172.16.0.1'
    environment:
      - SESSION_SECRET=REDACTED'
      - TZ=US/Eastern
    volumes:
      - /docker/zwave-js-ui/files:/usr/src/app/store
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_REDACTED-port0:/dev/zwave
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
    restart: 'unless-stopped'
    privileged: false
networks:
  docker_bridge:
    external: true
```

Checking the filesystem, cache files (I presume) are updated:

```
-rw-r--r--  1 root root  272778 May 23 08:25 dfeaaacd.values.jsonl
-rw-r--r--  1 root root 1777845 May 23 08:25 dfeaaacd.metadata.jsonl
drwxr-xr-x 11 root root    4096 May 23 08:25 .
-rw-r--r--  1 root root   66387 May 23 08:26 dfeaaacd.jsonl
drwxr-xr-x  2 root root    4096 May 23 08:28 dfeaaacd.values.jsonl.lock
drwxr-xr-x  2 root root    4096 May 23 08:28 dfeaaacd.metadata.jsonl.lock
drwxr-xr-x  2 root root    4096 May 23 08:28 dfeaaacd.jsonl.lock
```

And so are the config db files:

```
root@kurka:/docker/zwave-js-ui/files/.config-db# ls -la
total 52
drwxr-xr-x   3 root root  4096 May 21 22:41 .
drwxr-xr-x  11 root root  4096 May 23 08:28 ..
drwxr-xr-x 365 root root 12288 May 21 22:41 devices
-rw-r--r--   1 root root 26436 May 21 22:41 manufacturers.json
-rw-r--r--   1 root root     6 May 21 22:41 version
```

Default user does appear to have filesystem access:

```
root@kurka:/docker/zwave-js-ui/files/.config-db# docker exec -it zwave-js-ui sh
/usr/src/app # whoami
root
/usr/src/app # ls
dist          node_modules  package.json  server        snippets      store
/usr/src/app # cd store
/usr/src/app/store # ls
backups                       dfeaaacd.jsonl.lock           nodes.json
c7aad84d.jsonl                dfeaaacd.metadata.jsonl       sessions
c7aad84d.metadata.jsonl       dfeaaacd.metadata.jsonl.lock  settings.json
c7aad84d.values.jsonl         dfeaaacd.values.jsonl         snippets
config                        dfeaaacd.values.jsonl.lock    users.json
dfeaaacd.jsonl                logs
/usr/src/app/store # touch test.txt
/usr/src/app/store # rm test.txt
/usr/src/app/store # cd .config-db/
/usr/src/app/store/.config-db # touch test.txt
/usr/src/app/store/.config-db # rm test.txt
```

Out of curiosity, does zwave-js-ui docker support running as a non-root user (I am not doing this here, but have another server with more locked down docker instances where I have a regular user created on the host and pass the UID/GID to the container.)?
