### ISSUE TITLE
feat: consider adding watchtower support for automatic docker updates

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js-ui#4222]
```yml
services:
  zui: ....

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --http-api --http-api-update --monitor-only
    ports:
      - 8080:8080
```

API Docs: https://containrrr.dev/watchtower/http-api-mode/
